agent_config:
  agents:
    CdcCodegenAgent:
      agent_card:
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodegenAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:3b
        agent_name: CdcCodegenAgent
    CdcCodeSearchAgent:
      agent_card:
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodeSearchAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:3b
        agent_name: CdcCodeSearchAgent
    DeepCodeAgent:
      agent_card:
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:7b
        agent_name: DeepCodeAgent
profiles:
  active_profiles:
    main_profile:
      profile_name: main_profile
      priority: 1000000
  default_profile:
    profile_name: main_profile
    priority: 1000000
env_factories:
  factories:
    test:
      - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
        lazy: "False"
      - factory: python_di.inject.reflectable_ctx.ReflectableCtx
        lazy: "False"
      - factory: drools_py.inject.serialization_ctx.SerializationCtx
        lazy: "False"
