model_server:
  host: localhost
  port: 9991

agent_config:
  agents:
    CdcCodegenAgent:
      agent_card:
        name: CdcCodegenAgent
        url: localhost
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodegenAgent
      mcp_tools:
        postgres:
          name: postgres
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - mcp/postgres
              - postgresql://postgres:postgres@host.docker.internal:5450/postgres
            env:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:3b
        agent_name: CdcCodegenAgent
    CdcCodeSearchAgent:
      agent_card:
        name: CdcCodeSearchAgent
        url: localhost
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodeSearchAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:3b
        agent_name: CdcCodeSearchAgent
    DeepCodeAgent:
      agent_card:
        name: DeepCodeAgent
        url: localhost
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:7b
        agent_name: DeepCodeAgent
profiles:
  active_profiles:
    main_profile:
      profile_name: main_profile
env_factories:
  factories:
    - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
      lazy: "False"
    - factory: python_di.inject.reflectable_ctx.ReflectableCtx
      lazy: "False"
    - factory: drools_py.inject.serialization_ctx.SerializationCtx
      lazy: "False"
