tool_call:
  register_tool_calls: true

secrets:
  model_secrets:
    fake: fake
  mcp_tool_secrets:
    - tool_name: gitlab
      secret_name: X_GITLAB_TOKEN
      secret_value: ""
    - tool_name: github
      secret_name: X_GITHUB_TOKEN
      secret_value: ""

runner:
  runner_option: SKIP

cdc_server:
  graphql_endpoint: http://localhost:8080/graphql
model_server:
  host: localhost
  port: 9991

human_delegate:
  base_dir: ./human_delegate_data
checkpoint:
  uri: postgresql://postgres:postgres@localhost:5488/postgres?sslmode=disable

agent_config:
  orchestrator_max_recurs: 100
  agents:
    SummarizerAgent:
      enabled: false
      mcp_tools:
        memory:
          name: memory
          tool_prompt: >
            Save information to be recollected later for summarizing.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - -v
              - summarizer_memory:/app/dist
              - --rm
              - mcp/memory-summarizer
            env:
      options:
        max_tokens: 128000
        max_tokens_before_summary: 120000
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: SummarizerAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/SummarizerAgent.md
        system_prompts: file://prompts/system_prompts/SummarizerAgent.md
      agent_card:
        name: SummarizerAgent
        path: /summarizer
        description: file://prompts/description_prompts/SummarizerAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.summarizer_agent.SummarizerAgent
    LibraryEnumerationAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: LibraryEnumerationAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/LibraryEnumerationAgent.md
        system_prompts: file://prompts/system_prompts/LibraryEnumerationAgent.md
      agent_card:
        name: LibraryEnumerationAgent
        path: /library-enumeration
        description: file://prompts/description_prompts/LibraryEnumerationAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.library_enumeration_agent.LibraryEnumerationAgent
      mcp_tools:
        github:
          name: github
          tool_prompt: >
            Use Github to look up repository URLs for downstream tasks, as requested.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -e
              - GITHUB_PERSONAL_ACCESS_TOKEN={{X_GITHUB_TOKEN}}
              - mcp/github-library-enumeration
            env:
    HumanDelegateAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: HumanDelegateAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/HumanDelegateAgent.md
        system_prompts: file://prompts/system_prompts/HumanDelegateAgent.md
      agent_card:
        name: HumanDelegateAgent
        path: /human-delegate
        description: file://prompts/description_prompts/HumanDelegateAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.human_delegate_agent.HumanDelegateAgent
    CodeRunnerAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CodeRunnerAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/CodeRunnerAgent.md
        system_prompts: file://prompts/system_prompts/CodeRunnerAgent.md
      agent_card:
        name: CodeRunnerAgent
        path: /code-runner
        description: file://prompts/description_prompts/CodeRunnerAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.code_runner_agent.CodeRunnerAgent
      mcp_tools:
        git:
          stop_tool: container_id=$(docker ps | grep mcp/git-code-runner | awk '{print $1}') [ -n "$container_id" ] && docker stop "$container_id" >/dev/null 2>&1
          name: git
          tool_prompt: "Use git tool"
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects/drools:/Users/hayde/IdeaProjects/drools
              - mcp/git-code-runner
            env:
        filesystem:
          name: filesystem
          tool_prompt: >
            Use file system tool to search the file system for repositories, paths, or other data.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects:/Users/hayde/IdeaProjects
              - mcp/filesystem-code-runner
              - /Users/hayde/IdeaProjects
            env:
    CdcCodegenAgent:
      agent_card:
        name: CdcCodegenAgent
        path: /codegen
        version: 0.0.1
        description: file://prompts/description_prompts/CdcCodegenAgent.md
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodegenAgent
      mcp_tools:
        postgres:
          name: postgres
          tool_prompt: >
            Postgres can be used to search the database that contains the repository information.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - mcp/postgres-codegen
              - postgresql://postgres:postgres@host.docker.internal:5450/postgres
            env:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CdcCodegenAgent
        system_prompts: file://prompts/system_prompts/CdcCodegenAgent.md
        orchestrated_prompts: file://prompts/orchestrated_prompts/CdcCodegenAgent.md
    CdcCodeSearchAgent:
      agent_card:
        name: CdcCodeSearchAgent
        path: /code_search
        version: 0.0.1
        description: file://prompts/description_prompts/CdcCodeSearchAgent.md
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodeSearchAgent
      agent_descriptor:
        #        model: anthropic_chat://anthropic_chat/claude-3-5-sonnet-20241022
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CdcCodeSearchAgent
        system_prompts: file://prompts/system_prompts/CdcCodeSearchAgent.md
        orchestrated_prompts: file://prompts/orchestrated_prompts/CdcCodeSearchAgent.md
      mcp_tools:
        filesystem:
          name: filesystem
          tool_prompt: >
            Use file system tool to search the file system for repositories, paths, or other data.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects:/Users/hayde/IdeaProjects
              - mcp/filesystem-code-search
              - /Users/hayde/IdeaProjects
            env:
        git:
          stop_tool: container_id=$(docker ps | grep mcp/git-code-runner | awk '{print $1}') [ -n "$container_id" ] && docker stop "$container_id" >/dev/null 2>&1
          name: git
          tool_prompt: "Use git tool"
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects/drools:/Users/hayde/IdeaProjects/drools
              - mcp/git-code-search
            env:
    DeepCodeOrchestrator:
      agent_card:
        name: DeepCodeOrchestrator
        path: /deep-code-orchestrator
        version: 0.0.1
        description: file://prompts/description_prompts/DeepCodeOrchestrator.md
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeOrchestrator
      agent_descriptor:
        agent_name: DeepCodeOrchestrator
        model: ollama_chat://ollama_chat/phi4:14b
        orchestrated_prompts: >
        orchestrator_system_prompt: >
    DeepCodeAgent:
      agent_card:
        name: DeepCodeAgent
        path: /deep-code
        version: 0.0.1
        description: file://prompts/description_prompts/DeepCodeAgent.md
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/phi4:14b
        agent_name: DeepCodeAgent
        orchestrated_prompts: >
        system_prompts: file://prompts/system_prompts/DeepCodeAgent.md
        orchestrator_system_prompt: file://prompts/orchestrator_system_prompts/DeepCodeAgent.md

profiles:
  active_profiles:
    main_profile:
      profile_name: main_profile
env_factories:
  factories:
    - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
      lazy: "False"
    - factory: python_di.inject.reflectable_ctx.ReflectableCtx
      lazy: "False"
    - factory: drools_py.inject.serialization_ctx.SerializationCtx
      lazy: "False"
