tool_call:
  register_tool_calls: true

secrets:
  model_secrets:
    fake: fake
  mcp_tool_secrets:
    - tool_name: gitlab
      secret_name: X_GITLAB_TOKEN
      secret_value: ""
    - tool_name: github
      secret_name: X_GITHUB_TOKEN
      secret_value: ""

runner:
  runner_option: SKIP

cdc_server:
  graphql_endpoint: http://localhost:8080/graphql
model_server:
  host: localhost
  port: 9991

human_delegate:
  base_dir: ./human_delegate_data
checkpoint:
  uri: postgresql://postgres:postgres@localhost:5488/postgres?sslmode=disable

agent_config:
  orchestrator_max_recurs: 100
  agents:
    SummarizerAgent:
      exposed_externally: false
      mcp_tools:
        memory:
          name: memory
          tool_prompt: >
            Save information to be recollected later for summarizing.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - -v
              - summarizer_memory:/app/dist
              - --rm
              - mcp/memory-summarizer
            env:
      options:
        max_tokens: 128000
        max_tokens_before_summary: 120000
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: SummarizerAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/SummarizerAgent.md
        system_prompts: file://prompts/system_prompts/SummarizerAgent.md
      agent_card:
        name: SummarizerAgent
        path: /summarizer
        description: file://prompts/description_prompts/SummarizerAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.summarizer_agent.SummarizerAgent
    LibraryEnumerationAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: LibraryEnumerationAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/LibraryEnumerationAgent.md
        system_prompts: file://prompts/system_prompts/LibraryEnumerationAgent.md
      agent_card:
        name: LibraryEnumerationAgent
        path: /library-enumeration
        description: file://prompts/description_prompts/LibraryEnumerationAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.library_enumeration_agent.LibraryEnumerationAgent
      mcp_tools:
        github:
          name: github
          tool_prompt: >
            Use Github to look up repository URLs for downstream tasks, as requested.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -e
              - GITHUB_PERSONAL_ACCESS_TOKEN={{X_GITHUB_TOKEN}}
              - mcp/github-library-enumeration
            env:
    HumanDelegateAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: HumanDelegateAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/HumanDelegateAgent.md
        system_prompts: file://prompts/system_prompts/HumanDelegateAgent.md
      agent_card:
        name: HumanDelegateAgent
        path: /human-delegate
        description: file://prompts/description_prompts/HumanDelegateAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.human_delegate_agent.HumanDelegateAgent
    TestRunnerAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestRunnerAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestRunnerAgent.md
        system_prompts: file://prompts/system_prompts/TestRunnerAgent.md
      agent_card:
        name: TestRunnerAgent
        path: /test-runner
        description: file://prompts/description_prompts/TestRunnerAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.test_runner_agent.TestRunnerAgent
    CodeBuildAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CodeBuildAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/CodeBuildAgent.md
        system_prompts: file://prompts/system_prompts/CodeBuildAgent.md
      agent_card:
        name: CodeBuildAgent
        path: /code-build
        description: file://prompts/description_prompts/CodeBuildAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.code_build_agent.CodeBuildAgent
    CodeDeployAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CodeDeployAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/CodeDeployAgent.md
        system_prompts: file://prompts/system_prompts/CodeDeployAgent.md
      agent_card:
        name: CodeDeployAgent
        path: /code-deploy
        description: file://prompts/description_prompts/CodeDeployAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.code_deploy_agent.CodeDeployAgent
    CdcCodegenAgent:
      agent_card:
        name: CdcCodegenAgent
        path: /codegen
        version: 0.0.1
        description: file://prompts/description_prompts/CdcCodegenAgent.md
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodegenAgent
      mcp_tools:
        postgres:
          name: postgres
          tool_prompt: >
            Postgres can be used to search the database that contains the repository information.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - mcp/postgres-codegen
              - postgresql://postgres:postgres@host.docker.internal:5450/postgres
            env:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CdcCodegenAgent
        system_prompts: file://prompts/system_prompts/CdcCodegenAgent.md
        orchestrated_prompts: file://prompts/orchestrated_prompts/CdcCodegenAgent.md
    CdcCodeSearchAgent:
      agent_card:
        name: CdcCodeSearchAgent
        path: /code_search
        version: 0.0.1
        description: file://prompts/description_prompts/CdcCodeSearchAgent.md
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodeSearchAgent
      agent_descriptor:
        #        model: anthropic_chat://anthropic_chat/claude-3-5-sonnet-20241022
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: CdcCodeSearchAgent
        system_prompts: file://prompts/system_prompts/CdcCodeSearchAgent.md
        orchestrated_prompts: file://prompts/orchestrated_prompts/CdcCodeSearchAgent.md
      mcp_tools:
        filesystem:
          name: filesystem
          tool_prompt: >
            Use file system tool to search the file system for repositories, paths, or other data.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects:/Users/hayde/IdeaProjects
              - mcp/filesystem-code-search
              - /Users/hayde/IdeaProjects
            env:
        git:
          stop_tool: container_id=$(docker ps | grep mcp/git-code-runner | awk '{print $1}') [ -n "$container_id" ] && docker stop "$container_id" >/dev/null 2>&1
          name: git
          tool_prompt: "Use git tool"
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects/drools:/Users/hayde/IdeaProjects/drools
              - mcp/git-code-search
            env:
    DeepCodeOrchestrator:
      agent_card:
        name: DeepCodeOrchestrator
        path: /deep-code-orchestrator
        version: 0.0.1
        description: file://prompts/description_prompts/DeepCodeOrchestrator.md
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeOrchestrator
      agent_descriptor:
        agent_name: DeepCodeOrchestrator
        model: ollama_chat://ollama_chat/phi4:14b
        orchestrated_prompts: >
        orchestrator_system_prompt: >
        orchestrator_graph_agent_completion_prompt: file://prompts/orchestrator_graph_agent_completion_prompts/StateGraphOrchestratorAgentCompletion.md
        orchestrator_graph_agent_tool_completion_prompt: file://prompts/orchestrator_graph_agent_completion_prompts/StateGraphOrchestratorAgentToolCompletion.md
    DeepCodeAgent:
      exposed_externally: false
      agent_card:
        name: DeepCodeAgent
        path: /deep-code
        version: 0.0.1
        description: file://prompts/description_prompts/DeepCodeAgent.md
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/phi4:14b
        agent_name: DeepCodeAgent
        orchestrated_prompts: >
        system_prompts: file://prompts/system_prompts/DeepCodeAgent.md
        orchestrator_system_prompt: file://prompts/orchestrator_system_prompts/DeepCodeAgent.md
    TestGraphAgent:
      exposed_externally: false
      agent_card:
        name: TestGraphAgent
        path: /test-graph
        version: 0.0.1
        description: file://prompts/description_prompts/TestGraphAgent.md
      agent_clazz: cdc_agents.agents.test_graph.test_graph_agent_orchestrator.TestGraphAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/phi4:14b
        agent_name: TestGraphAgent
        orchestrated_prompts: >
        system_prompts: file://prompts/system_prompts/TestGraphAgent.md
        orchestrator_system_prompt: file://prompts/orchestrator_system_prompts/TestGraphAgent.md
    TestGraphOrchestrator:
      agent_card:
        name: TestGraphOrchestrator
        path: /test-graph-orchestrator
        version: 0.0.1
        description: file://prompts/description_prompts/TestGraphOrchestrator.md
      agent_clazz: cdc_agents.agents.test_graph.test_graph_agent_orchestrator.TestGraphOrchestrator
      agent_descriptor:
        agent_name: TestGraphOrchestrator
        model: ollama_chat://ollama_chat/phi4:14b
        orchestrated_prompts: >
        orchestrator_system_prompt: >
        orchestrator_propagator_prompt: file://prompts/orchestrator_propagator_prompts/TestGraphOrchestrator.md
        orchestrator_graph_agent_completion_prompt: file://prompts/orchestrator_graph_agent_completion_prompts/StateGraphOrchestratorAgentCompletion.md
        orchestrator_graph_agent_tool_completion_prompt: file://prompts/orchestrator_graph_agent_completion_prompts/StateGraphOrchestratorAgentToolCompletion.md
    TestGraphCdcCodeSearchAgent:
      agent_card:
        name: TestGraphCdcCodeSearchAgent
        path: /test-graph-code-search
        version: 0.0.1
        description: file://prompts/description_prompts/TestGraphCdcCodeSearchAgent.md
      agent_clazz: cdc_agents.agents.test_graph.test_graph_cdc_code_search_agent.TestGraphCdcCodeSearchAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphCdcCodeSearchAgent
        system_prompts: file://prompts/system_prompts/TestGraphCdcCodeSearchAgent.md
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphCdcCodeSearchAgent.md
      mcp_tools:
        filesystem:
          name: filesystem
          tool_prompt: >
            Use file system tool to search the file system for test repositories, test paths, and test-related data.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects:/Users/hayde/IdeaProjects
              - mcp/filesystem-code-search
              - /Users/hayde/IdeaProjects
            env:
        git:
          stop_tool: container_id=$(docker ps | grep mcp/git-code-runner | awk '{print $1}') [ -n "$container_id" ] && docker stop "$container_id" >/dev/null 2>&1
          name: git
          tool_prompt: "Use git tool for test repository operations"
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -v
              - /Users/hayde/IdeaProjects/drools:/Users/hayde/IdeaProjects/drools
              - mcp/git-code-search
            env:
    TestGraphCodeBuildAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphCodeBuildAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphCodeBuildAgent.md
        system_prompts: file://prompts/system_prompts/TestGraphCodeBuildAgent.md
      agent_card:
        name: TestGraphCodeBuildAgent
        path: /test-graph-code-build
        description: file://prompts/description_prompts/TestGraphCodeBuildAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.test_graph.test_graph_code_build_agent.TestGraphCodeBuildAgent
    TestGraphCdcCodegenAgent:
      agent_card:
        name: TestGraphCdcCodegenAgent
        path: /test-graph-codegen
        version: 0.0.1
        description: file://prompts/description_prompts/TestGraphCdcCodegenAgent.md
      agent_clazz: cdc_agents.agents.test_graph.test_graph_cdc_codegen_agent.TestGraphCdcCodegenAgent
      mcp_tools:
        postgres:
          name: postgres
          tool_prompt: >
            Postgres can be used to search the test database that contains the repository information for test generation.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - mcp/postgres-codegen
              - postgresql://postgres:postgres@host.docker.internal:5450/postgres
            env:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphCdcCodegenAgent
        system_prompts: file://prompts/system_prompts/TestGraphCdcCodegenAgent.md
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphCdcCodegenAgent.md
    TestGraphCodeDeployAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphCodeDeployAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphCodeDeployAgent.md
        system_prompts: file://prompts/system_prompts/TestGraphCodeDeployAgent.md
      agent_card:
        name: TestGraphCodeDeployAgent
        path: /test-graph-code-deploy
        description: file://prompts/description_prompts/TestGraphCodeDeployAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.test_graph.test_graph_code_deploy_agent.TestGraphCodeDeployAgent
    TestGraphTestRunnerAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphTestRunnerAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphTestRunnerAgent.md
        system_prompts: file://prompts/system_prompts/TestGraphTestRunnerAgent.md
      agent_card:
        name: TestGraphTestRunnerAgent
        path: /test-graph-test-runner
        description: file://prompts/description_prompts/TestGraphTestRunnerAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.test_graph.test_graph_test_runner_agent.TestGraphTestRunnerAgent
    TestGraphHumanDelegateAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphHumanDelegateAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphHumanDelegateAgent.md
        system_prompts: file://prompts/system_prompts/TestGraphHumanDelegateAgent.md
      agent_card:
        name: TestGraphHumanDelegateAgent
        path: /test-graph-human-delegate
        description: file://prompts/description_prompts/TestGraphHumanDelegateAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.test_graph.test_graph_human_delegate_agent.TestGraphHumanDelegateAgent
    TestGraphLibraryEnumerationAgent:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphLibraryEnumerationAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphLibraryEnumerationAgent.md
        system_prompts: file://prompts/system_prompts/TestGraphLibraryEnumerationAgent.md
      agent_card:
        name: TestGraphLibraryEnumerationAgent
        path: /test-graph-library-enumeration
        description: file://prompts/description_prompts/TestGraphLibraryEnumerationAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.test_graph.test_graph_library_enumeration_agent.TestGraphLibraryEnumerationAgent
      mcp_tools:
        github:
          name: github
          tool_prompt: >
            Use Github to look up test-related repository URLs and test library dependencies for downstream tasks, as requested.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - -e
              - GITHUB_PERSONAL_ACCESS_TOKEN={{X_GITHUB_TOKEN}}
              - mcp/github-library-enumeration
            env:
    TestGraphSummarizerAgent:
      exposed_externally: false
      mcp_tools:
        memory:
          name: memory
          tool_prompt: >
            Save test execution information to be recollected later for test summarizing and reporting.
          tool_options:
            command: docker
            args:
              - run
              - -i
              - -v
              - test_graph_summarizer_memory:/app/dist
              - --rm
              - mcp/memory-summarizer
            env:
      options:
        max_tokens: 128000
        max_tokens_before_summary: 120000
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:8b
        agent_name: TestGraphSummarizerAgent
        orchestrated_prompts: file://prompts/orchestrated_prompts/TestGraphSummarizerAgent.md
        system_prompts: file://prompts/system_prompts/TestGraphSummarizerAgent.md
      agent_card:
        name: TestGraphSummarizerAgent
        path: /test-graph-summarizer
        description: file://prompts/description_prompts/TestGraphSummarizerAgent.md
        version: 0.0.1
      agent_clazz: cdc_agents.agents.test_graph.test_graph_summarizer_agent.TestGraphSummarizerAgent

profiles:
  active_profiles:
    main_profile:
      profile_name: main_profile
env_factories:
  factories:
    - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
      lazy: "False"
    - factory: python_di.inject.reflectable_ctx.ReflectableCtx
      lazy: "False"
    - factory: drools_py.inject.serialization_ctx.SerializationCtx
      lazy: "False"
