model_server:
  host: localhost
  port: 9991

checkpoint:
  uri:

agent_config:
  agents:
#    CodeRunnerAgent:
#      name: CodeRunnerAgent
#      path: /coderunner
#      version: 0.0.1
#      agent_clazz: cdc_agents.agent.agent.code_runner_agent.CodeRunnerAgent
#      mcp_tools:
#        postgres:
#          name: postgres
#          tool_prompt: "Use postgres tool"
#          tool_options:
#            command: docker
#            args:
#              - run
#              - -i
#              - --rm
#              - mcp/code-runner-postgres
#              - postgresql://postgres:postgres@host.docker.internal:5450/postgres
#            env:
#        git:
#          stop_tool: docker stop $(docker ps | grep mcp/code-runner-git | cut -d' ' -f1)
#          name: git
#          tool_prompt: "Use git tool"
##          exec_tool_options:
##            command: docker
##            args:
##              - exec
##              - -i
##              - mcp/code-runner-git
##            env:
#          tool_options:
#            command: docker
#            args:
#              - run
#              - -i
#              - --rm
#              - --mount type=bind,src=/Users/
#              - mcp/code-runner-git
#            env:
#        filesystem:
#          name: filesystem
#          tool_prompt: "Use file system tool to search the file system for repositories, paths, or other data."
#          tool_options:
#            command: docker
#            args:
#              - run
#              - -i
#              - --rm
#              - --mount type=bind,src=/Users/
#              - mcp/code-runner-filesystem
#              - /Users/hayde
#            env:
#        docker:
#          tool_prompt: "Use docker to build the container. Please note the directory provided by the user."
#          name: docker
#          tool_options:
#            command: docker
#            args:
#              - run
#              - -i
#              - --rm
#              - -v
#              - /var/run/docker.sock:/var/run/docker.sock
#              - mcp/code-runner-docker
#            env:
    CdcCodegenAgent:
      agent_card:
        name: CdcCodegenAgent
        path: /codegen
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodegenAgent
      mcp_tools:
        postgres:
          name: postgres
          tool_prompt: "Use postgres tool"
          tool_options:
            command: docker
            args:
              - run
              - -i
              - --rm
              - mcp/postgres
              - postgresql://postgres:postgres@host.docker.internal:5450/postgres
            env:
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:3b
        agent_name: CdcCodegenAgent
    CdcCodeSearchAgent:
      agent_card:
        name: CdcCodeSearchAgent
        path: /code_search
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.cdc_server_agent.CdcCodeSearchAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:3b
        agent_name: CdcCodeSearchAgent
    DeepCodeAgent:
      agent_card:
        name: DeepCodeAgent
        path: /deep_code
        version: 0.0.1
      agent_clazz: cdc_agents.agent.agent.deep_code_research_agent.DeepCodeAgent
      agent_descriptor:
        model: ollama_chat://ollama_chat/hermes3:7b
        agent_name: DeepCodeAgent
profiles:
  active_profiles:
    main_profile:
      profile_name: main_profile
env_factories:
  factories:
    - factory: python_di.inject.context_builder.factory_ctx.FactoryCtx
      lazy: "False"
    - factory: python_di.inject.reflectable_ctx.ReflectableCtx
      lazy: "False"
    - factory: drools_py.inject.serialization_ctx.SerializationCtx
      lazy: "False"
