# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.10-bookworm-slim AS uv

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
#ENV UV_LINK_MODE=copy
RUN apt-get update && \
    apt-get install -y ca-certificates curl gnupg && \
    install -m 0755 -d /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    rm -rf /var/lib/apt/lists/*

COPY ./build /home/cdc_agents/sources

ENV PATH="/app/.venv/bin:/uv:$PATH"

COPY ./build/.env /home/cdc_agents/sources/.env
COPY ./build/test /home/cdc_agents/sources/test
COPY ./build/src /home/cdc_agents/sources/src

WORKDIR /home/cdc_agents/sources

# when running the container, add --db-path and a bind mount to the host's db file
ENTRYPOINT ["uv", "run", "test-cdc-agents"]
