# Use a Python image with uv pre-installed
FROM cdc_agents_base:latest

# when running the container, add --db-path and a bind mount to the host's db file

ENV SPRING_PROFILES_ACTIVE='a2a,docker'

ENTRYPOINT ["uv", "run", "run-cdc-agents"]
