import json
import typing
import unittest.mock

import pydantic
from langchain.agents.output_parsers import JSONAgentOutputParser, ReActSingleInputOutputParser
from langgraph.checkpoint.memory import MemorySaver
from starlette.applications import Starlette

from cdc_agents.agent.agent_server import AgentServerRunner
from cdc_agents.agent.response_format_parser import ResponseFormatParser
from cdc_agents.agents.cdc_server_agent import CdcCodeSearchAgent
from cdc_agents.agents.code_build_agent import CodeBuildAgent
from cdc_agents.agents.code_deploy_agent import CodeDeployAgent
from cdc_agents.agents.deep_code_research_agent import DeepCodeOrchestrator, DeepCodeAgent
from cdc_agents.agents.human_delegate_agent import HumanDelegateAgent
from cdc_agents.agents.library_enumeration_agent import LibraryEnumerationAgent
from cdc_agents.agents.summarizer_agent import SummarizerAgent
from cdc_agents.agents.test_graph.test_graph_agent_orchestrator import TestGraphOrchestrator
from cdc_agents.agents.test_runner_agent import TestRunnerAgent
from cdc_agents.config.agent_config_props import AgentConfigProps
from cdc_agents.config.cdc_server_config_props import CdcServerConfigProps
from cdc_agents.config.checkpoint_config_props import CheckpointConfigProps
from cdc_agents.config.human_delegate_config_props import HumanDelegateConfigProps
from cdc_agents.config.model_server_config_props import ModelServerConfigProps
from cdc_agents.config.runner_props import RunnerConfigProps
from cdc_agents.config.secret_config_props import SecretConfigProps
from cdc_agents.config.tool_call_properties import ToolCallProps
from cdc_agents.model_server.model_provider import ModelProvider
from cdc_agents.model_server.model_server_model import ModelServerModel
from cdc_agents.tools.tool_call_decorator import ToolCallDecorator
from python_di.configs.bean import bean
from python_di.configs.component_scan import component_scan
from python_di.configs.di_configuration import configuration
from python_di.configs.enable_configuration_properties import enable_configuration_properties
from python_di.inject.profile_composite_injector.composite_injector import profile_scope
from python_util.logger.logger import LoggerFacade
from langgraph.checkpoint.serde.base import UntypedSerializerProtocol, SerializerCompat
from pydantic import BaseModel
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, FunctionMessage, ToolMessage

# @component_scan(base_classes=[TestGraphOrchestrator])
class TestGraphConfig:
    pass

